### ISSUE TITLE
No license is specified

### ISSUE THREAD

**Issue by kuzm** [habaneroofdoom/AltNetRop#1]
Hi! This is a nice implementation of ROP. I would be happy if I could use it in my projects but I'm unsure under which license you published this code. Could you explicitly specify a license e.g. Apache 2.0 or MIT? Also, if you borrowed some code, could you specify its license too?

**Comment by habaneroofdoom** [comment]
Hey there, glad you found it of some value. Apart from being inspired by Scott Wlaschin's work (referenced in Readme) there's nothing borrowed, so go ahead and use it as you wish. I've added an MIT license to the repo now.

**Comment by kuzm** [comment]
Thanks!
